services:
  app:
    build: .
    image: chat_bot_image:latest
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - ./data/botclientes:/root/botclientes
      - ./data/Dropbox:/root/Dropbox
    env_file:
      - .env
    environment:
      - DEVELOPMENT=true
    command: python manage.py runserver 0.0.0.0:8081
    networks:
      - main

networks:
  main:
    external: true
