services:
  app:
    container_name: chat_bot_app_prod
    build: .
    image: chat_bot_image:latest
    env_file:
      - .env
    volumes:
      - ./data/botclientes:/root/botclientes
      - ./data/Dropbox:/root/Dropbox
    restart: always
    command: gunicorn --bind 0.0.0.0:8081 idsa.wsgi:application
    networks:
      - main

  nginx:
    image: nginx:latest
    container_name: nginx_chat_bot_prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./staticfiles:/staticfiles:ro
    depends_on:
      - app
    networks:
      - main

networks:
  main:
    external: true