services:
  app:
    image: chat_bot_image:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./data/botclientes:/root/botclientes
      - ./data/Dropbox:/root/Dropbox
    restart: always
    command: gunicorn --bind 0.0.0.0:8081 idsa.wsgi:application
    networks:
      - main

networks:
  main:
    external: true