services:
  app:
    container_name: chat_bot_app
    image: chat_bot_image
    env_file:
      - .env
    build: .
    restart: on-failure # always # dejar always cuando este en el servidor
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - ./data/botclientes:/root/botclientes
      - ./data/Dropbox:/root/Dropbox
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
    name: bot_network