[tool.black]
line-length = 128
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.vscode
  | __pycache__
  | logs
  | nginx
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 128
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 128
extend-ignore = [
    "E203",  # Conflicto con Black
    "W503",  # Conflicto con Black
    "E501",  # Black puede dejar líneas más largas por consistencia, ejecutar black primero
]
exclude = [
    ".git",
    ".mypy_cache",
    ".vscode",
    "__pycache__",
    "logs",
    "nginx",
    "migrations"
]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
warn_unused_configs = true
show_error_codes = true
pretty = true
exclude = [
    ".git",
    ".mypy_cache",
    ".vscode",
    "__pycache__",
    "logs",
    "nginx",
    "migrations",
    "manage.py",
    "idsa/urls.py",
]