# Generated by Django 5.1.6 on 2025-04-14 02:42

import django.db.models.deletion
from django.db import migrations, models


def create_initials(apps, schema_editor):
    DatabaseDriver = apps.get_model('app_bot_hibrido', 'DatabaseDriver')
    DatabaseDriver.objects.bulk_create([
        DatabaseDriver(description="mysql", driver="mysql+pymysql"),
        DatabaseDriver(description="postgresql", driver="postgresql+psycopg2"),
        DatabaseDriver(description="sqlserver", driver="mssql+pyodbc"),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('app_bot_hibrido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Database Driver',
                'verbose_name_plural': 'Database Drivers',
            },
        ),
        migrations.RunPython(create_initials),
        migrations.CreateModel(
            name='ExternalDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('database', models.CharField(max_length=255)),
                ('driver', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_db', to='app_bot_hibrido.client')),
                ('db_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bot_hibrido.databasedriver')),
            ],
            options={
                'verbose_name': 'External Database',
                'verbose_name_plural': 'External Databases',
            },
        ),
    ]
